/* JAM.java */
/* Generated By:JavaCC: Do not edit this line. JAM.java */
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.LinkedList;
import java.util.Scanner;
import java.util.HashMap;
import java.util.Map;
import java.util.Stack;

// Classe principal
public class JAM implements JAMConstants {
  public static LinkedList < InfoToken > reservada = new LinkedList < > ();
  public static LinkedList < InfoToken > simbolo = new LinkedList < > ();
  public static Stack < Map < String, String > > tabelaSemantica = new Stack < > ();
  private static final int MAX = 32;

  public void erroSemantico(String mensagem, Token t) {
                    System.err.println("Erro sem\u00e2ntico (Linha: " + t.beginLine + ", Coluna: " + t.beginColumn + "): " + mensagem);
  }

  public void escreverArvoresEmArquivo(LinkedList < No > arvores, String nomeArquivo) throws IOException {
    FileWriter writer = new FileWriter(nomeArquivo);
    writer.write("--- IN\u00cdCIO DA \u00c1RVORE SINT\u00c1TICA ---\n\n");
    for (No raiz : arvores)
    {
      escreverNoRecursivo(raiz, 0, writer);
      writer.write("\n");
    }
    writer.write("--- FIM DA \u00c1RVORE SINT\u00c1TICA ---\n");
    writer.close();
  }

  private void escreverNoRecursivo(No no, int nivel, FileWriter writer) throws IOException {
    if (no == null) {
        return;
        }

    for (int i = 0; i < nivel; i++) {
      writer.write("  ");
    }
    writer.write("- " + no.tipo);
    if (no.valor != null) {
      writer.write(": <" + no.valor + ">");
    }
    writer.write("\n");
    for (No filho : no.filhos) {
      escreverNoRecursivo(filho, nivel + 1, writer);
    }
  }

  public static void main(String [] args) throws ParseException, TokenMgrError, FileNotFoundException {
    JAM parser;
    FileInputStream arquivo;
    Scanner scanner = new Scanner(System.in);
    int opcao;

    System.out.print("Insira o nome do arquivos: ");
    try {
      arquivo = new FileInputStream(scanner.nextLine());
    } catch(FileNotFoundException e) {
      System.out.println(e);
      return;
    }
    try {
      parser = new JAM(arquivo);
      parser.inicializar_programa();
                do {
                System.out.println("1 - Imprimir tabela de simbolos");
                System.out.println("2 - Imprimir tabela de palavras reservadas");
                System.out.println("0 - Sair");
                System.out.print("Selecione uma opcao:");
                opcao = scanner.nextInt();

                switch (opcao){
                  case 1 :
                          imprimirTokens(simbolo);
                          break;
                  case 2 :
                          imprimirTokens(reservada);
                          break;
                  case 0 :
                          System.out.println("Obrigado!!");
                          break;
                  default :
                          System.out.println("Op\u00e7\u00e3o incorreta!");
                          break;
                }
              }while (opcao != 0);
    } catch (TokenMgrError e) {
      System.out.println("Erro l\u00e9xico: " + e.getMessage());
    } catch (ParseException e) {
      System.out.println("Erro de sintaxe: " + e.getMessage());
    }
    scanner.close();
  }

  public void inserirTokenUnico(LinkedList < InfoToken > l, String tipo, Token t) {
    for (InfoToken tok : l) {
      if (tok.lexema.equals(t.image)) {
        return;
      }
    }
    l.add(new InfoToken(tipo, t.image, t.beginLine, t.beginColumn));
  }

  public static void imprimirTokens(LinkedList < InfoToken > l) {
    if (l.isEmpty()) {
      System.out.println("Lista vazia");
      return;
    }
    for (InfoToken tok : l) {
      System.out.println(tok);
    }
  }

// 1. BIBLIOTECAS
  final public void inicializar_programa() throws ParseException {LinkedList < No > arvores = new LinkedList < > ();
  No arvoreAtual;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_VOID:
      case TOKEN_INT:
      case TOKEN_FLOAT:
      case TOKEN_DOUBLE:
      case TOKEN_CHAR:
      case TOKEN_BOOL:
      case TOKEN_IMPORT:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_IMPORT:{
        arvoreAtual = inclusao_biblioteca();
if (arvoreAtual != null)
                        arvores.add(arvoreAtual);
        break;
        }
      case TOKEN_VOID:
      case TOKEN_INT:
      case TOKEN_FLOAT:
      case TOKEN_DOUBLE:
      case TOKEN_CHAR:
      case TOKEN_BOOL:{
        arvoreAtual = criar_funcoes();
if (arvoreAtual != null)
                                arvores.add(arvoreAtual);
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(0);
System.out.println("An\u00e1lise sint\u00e1tica finalizada");
            try {
              escreverArvoresEmArquivo(arvores, "arvores_fonte1.txt");
              System.out.println("Arquivo arvores_fonte1.txt gerado.\n");
            } catch (IOException e) {
              System.err.println("Erro ao escrever o arquivo da \u00e1rvore: " + e.getMessage());
            }
}

  final public No inclusao_biblioteca() throws ParseException {Token t;
  No noImport = new No("IMPORT");
    t = jj_consume_token(TOKEN_IMPORT);
inserirTokenUnico(reservada, "IMPORT", t);
    t = jj_consume_token(STRING);
noImport.adicionarFilho(new No("BIBLIOTECA", t.image));
    inserirTokenUnico(simbolo, "STRING", t);
    t = jj_consume_token(PONTO_VIRGULA);
inserirTokenUnico(reservada, "PONTO_VIRGULA", t);
{if ("" != null) return noImport;}
    throw new Error("Missing return statement in function");
}

// 2. BLOCO DE COMANDOS
  final public No bloco_de_comandos() throws ParseException {No noBloco = new No("BLOCO_COMANDOS");
  No cmd;
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_IF:
      case TOKEN_WHILE:
      case TOKEN_FOR:
      case TOKEN_VOID:
      case TOKEN_INT:
      case TOKEN_FLOAT:
      case TOKEN_DOUBLE:
      case TOKEN_CHAR:
      case TOKEN_BOOL:
      case TOKEN_RETURN:
      case TOKEN_READ:
      case TOKEN_WRITE:
      case PONTO_VIRGULA:
      case IDENTIFICADOR:{
        ;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        break label_2;
      }
      // Para cada comando encontrado, captura seu nó e adiciona ao bloco
              cmd = comando();
noBloco.adicionarFilho(cmd);
    }
{if ("" != null) return noBloco;}
    throw new Error("Missing return statement in function");
}

// Regra unica de comando.
  final public No comando() throws ParseException {No noComando;
  Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_VOID:
    case TOKEN_INT:
    case TOKEN_FLOAT:
    case TOKEN_DOUBLE:
    case TOKEN_CHAR:
    case TOKEN_BOOL:{
      // 3. DECLARAÇÃO DE VARIÁVEIS
        noComando = declarar_variavel();
{if ("" != null) return noComando;}
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      if (jj_2_1(2)) {
        noComando = atribuicao();
{if ("" != null) return noComando;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFICADOR:{
          noComando = chamar_funcao();
{if ("" != null) return noComando;}
          break;
          }
        case TOKEN_IF:{
          noComando = if_else();
{if ("" != null) return noComando;}
          break;
          }
        case TOKEN_WHILE:{
          noComando = laco_while();
{if ("" != null) return noComando;}
          break;
          }
        case TOKEN_FOR:{
          noComando = laco_for();
{if ("" != null) return noComando;}
          break;
          }
        case TOKEN_RETURN:{
          noComando = retorno();
{if ("" != null) return noComando;}
          break;
          }
        case TOKEN_WRITE:{
          noComando = comando_escrita();
{if ("" != null) return noComando;}
          break;
          }
        case TOKEN_READ:{
          noComando = comando_leitura();
{if ("" != null) return noComando;}
          break;
          }
        case PONTO_VIRGULA:{
          t = jj_consume_token(PONTO_VIRGULA);
inserirTokenUnico(reservada, "PONTO_VIRGULA", t);
    {if ("" != null) return new No("COMANDO_VAZIO");}
          break;
          }
        default:
          jj_la1[4] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
}

// Estrutura condicional if/else.
  final public No if_else() throws ParseException {No noIf = new No("ESTRUTURA_IF");
  No condicao;
  No blocoPrincipal;
  No blocoSenao = null;
  Token t;
    t = jj_consume_token(TOKEN_IF);
inserirTokenUnico(reservada, "IF", t);
    t = jj_consume_token(ABRE_PARENTESIS);
inserirTokenUnico(reservada, "ABRE_PARENTESIS", t);
    condicao = expressao();
noIf.adicionarFilho(condicao);
    t = jj_consume_token(FECHA_PARENTESIS);
inserirTokenUnico(reservada, "FECHA_PARENTESIS", t);
    t = jj_consume_token(ABRE_CHAVES);
inserirTokenUnico(reservada, "ABRE_CHAVES", t);
    blocoPrincipal = bloco_de_comandos();
noIf.adicionarFilho(blocoPrincipal);
    t = jj_consume_token(FECHA_CHAVES);
inserirTokenUnico(reservada, "FECHA_CHAVES", t);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_ELSE:{
      blocoSenao = senao();
noIf.adicionarFilho(blocoSenao);
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
{if ("" != null) return noIf;}
    throw new Error("Missing return statement in function");
}

  final public No senao() throws ParseException {No noElse = new No("BLOCO_ELSE");
  No bloco;
  Token t;
    t = jj_consume_token(TOKEN_ELSE);
inserirTokenUnico(reservada, "ELSE", t);
    t = jj_consume_token(ABRE_CHAVES);
inserirTokenUnico(reservada, "ABRE_CHAVES", t);
    bloco = bloco_de_comandos();
noElse.adicionarFilho(bloco);
    t = jj_consume_token(FECHA_CHAVES);
inserirTokenUnico(reservada, "FECHA_CHAVES", t);
{if ("" != null) return noElse;}
    throw new Error("Missing return statement in function");
}

// Laço de repetição while.
  final public No laco_while() throws ParseException {No noWhile = new No("LACO_WHILE");
  No condicao;
  No bloco;
  Token t;
    t = jj_consume_token(TOKEN_WHILE);
inserirTokenUnico(reservada, "WHILE", t);
    t = jj_consume_token(ABRE_PARENTESIS);
inserirTokenUnico(reservada, "ABRE_PARENTESIS", t);
    condicao = expressao();
noWhile.adicionarFilho(condicao);
    t = jj_consume_token(FECHA_PARENTESIS);
inserirTokenUnico(reservada, "FECHA_PARENTESIS", t);
    t = jj_consume_token(ABRE_CHAVES);
inserirTokenUnico(reservada, "ABRE_CHAVES", t);
    bloco = bloco_de_comandos();
noWhile.adicionarFilho(bloco);
    t = jj_consume_token(FECHA_CHAVES);
inserirTokenUnico(reservada, "FECHA_CHAVES", t);
{if ("" != null) return noWhile;}
    throw new Error("Missing return statement in function");
}

// Laço de repetição for.
  final public No laco_for() throws ParseException {No noFor = new No("LACO_FOR");
  No inicializacao = null;
  No condicao = null;
  No incremento = null;
  No bloco;
  Token t;
    t = jj_consume_token(TOKEN_FOR);
inserirTokenUnico(reservada, "FOR", t);
    t = jj_consume_token(ABRE_PARENTESIS);
inserirTokenUnico(reservada, "ABRE_PARENTESIS", t);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      inicializacao = atribuicao_simples();
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
noFor.adicionarFilho(inicializacao != null ? inicializacao : new No("INICIALIZACAO_VAZIA"));
    t = jj_consume_token(PONTO_VIRGULA);
inserirTokenUnico(reservada, "PONTO_VIRGULA", t);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_TRUE:
    case TOKEN_FALSE:
    case SUBTRACAO:
    case NOT:
    case ABRE_PARENTESIS:
    case INTEIRO:
    case REAL:
    case IDENTIFICADOR:
    case STRING:{
      condicao = expressao();
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
noFor.adicionarFilho(condicao != null ? condicao : new No("CONDICAO_VAZIA"));
    t = jj_consume_token(PONTO_VIRGULA);
inserirTokenUnico(reservada, "PONTO_VIRGULA", t);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      incremento = atribuicao_simples();
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
noFor.adicionarFilho(incremento != null ? incremento : new No("INCREMENTO_VAZIO"));
    t = jj_consume_token(FECHA_PARENTESIS);
inserirTokenUnico(reservada, "FECHA_PARENTESIS", t);
    t = jj_consume_token(ABRE_CHAVES);
inserirTokenUnico(reservada, "ABRE_CHAVES", t);
    bloco = bloco_de_comandos();
noFor.adicionarFilho(bloco);
    t = jj_consume_token(FECHA_CHAVES);
inserirTokenUnico(reservada, "FECHA_CHAVES", t);
{if ("" != null) return noFor;}
    throw new Error("Missing return statement in function");
}

// Comando de escrita de dados.
  final public No comando_escrita() throws ParseException {No noWrite = new No("ESCRITA");
          No args;
          Token t;
    t = jj_consume_token(TOKEN_WRITE);
inserirTokenUnico(reservada, "WRITE", t);
    t = jj_consume_token(ABRE_PARENTESIS);
inserirTokenUnico(reservada, "ABRE_PARENTESIS", t);
    args = lista_de_argumentos();
noWrite.adicionarFilho(args);
    t = jj_consume_token(FECHA_PARENTESIS);
inserirTokenUnico(reservada, "FECHA_PARENTESIS", t);
    t = jj_consume_token(PONTO_VIRGULA);
inserirTokenUnico(reservada, "PONTO_VIRGULA", t);
{if ("" != null) return noWrite;}
    throw new Error("Missing return statement in function");
}

// Comando de leitura de dados.
  final public No comando_leitura() throws ParseException {Token t;
  No noRead = new No("LEITURA");
    t = jj_consume_token(TOKEN_READ);
inserirTokenUnico(reservada, "READ", t);
    t = jj_consume_token(ABRE_PARENTESIS);
inserirTokenUnico(reservada, "ABRE_PARENTESIS", t);
    t = jj_consume_token(IDENTIFICADOR);
noRead.adicionarFilho(new No("IDENTIFICADOR", t.image));
    inserirTokenUnico(simbolo, "IDENTIFICADOR", t);

    if (t.image.length() > MAX) {
      System.out.println("AVISO: IDENTIFICADOR_LONGO: " + t.image);
    }
    t = jj_consume_token(FECHA_PARENTESIS);
inserirTokenUnico(reservada, "FECHA_PARENTESIS", t);
    t = jj_consume_token(PONTO_VIRGULA);
inserirTokenUnico(reservada, "PONTO_VIRGULA", t);
{if ("" != null) return noRead;}
    throw new Error("Missing return statement in function");
}

// Comando de retorno de função.
  final public No retorno() throws ParseException {No noReturn = new No("RETORNO");
  No expr = null;
  Token t;
    t = jj_consume_token(TOKEN_RETURN);
inserirTokenUnico(reservada, "RETURN", t);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_TRUE:
    case TOKEN_FALSE:
    case SUBTRACAO:
    case NOT:
    case ABRE_PARENTESIS:
    case INTEIRO:
    case REAL:
    case IDENTIFICADOR:
    case STRING:{
      expr = expressao();
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
if (expr != null) noReturn.adicionarFilho(expr);
    t = jj_consume_token(PONTO_VIRGULA);
inserirTokenUnico(reservada, "PONTO_VIRGULA", t);
{if ("" != null) return noReturn;}
    throw new Error("Missing return statement in function");
}

// 11. ATRIBUIÇÕES
  final public No atribuicao() throws ParseException {Token t;
  No noAtrib = new No("ATRIBUICAO");
  No expr;
  String tipoVariavel = "unknown";
    t = jj_consume_token(IDENTIFICADOR);
noAtrib.adicionarFilho(new No("IDENTIFICADOR", t.image));

                if (tabelaSemantica.lastElement().containsKey(t.image)) {
                        tipoVariavel = tabelaSemantica.lastElement().get(t.image);
                }
                else {
                        erroSemantico("Vari\u00e1vel n\u00e3o declarada: " + t.image, t);
                }
    t = jj_consume_token(ATRIBUICAO);
inserirTokenUnico(reservada, "ATRIBUICAO", t);
    expr = expressao();
noAtrib.adicionarFilho(expr);

            if (!tipoVariavel.equals("unknown") && expr.tipoDado != null && !expr.tipoDado.equals("erro")) {
              if (!tipoVariavel.equals(expr.tipoDado)) {
                erroSemantico("Tipos incompat\u00edveis: vari\u00e1vel do tipo '" + tipoVariavel + "', recebe uma express\u00e3o do tipo: " + expr.tipoDado, t);
              }
            }
    t = jj_consume_token(PONTO_VIRGULA);
inserirTokenUnico(reservada, "PONTO_VIRGULA", t);
{if ("" != null) return noAtrib;}
    throw new Error("Missing return statement in function");
}

// Regra auxiliar para o laço 'for', que é uma atribuição sem o ponto e vírgula final.
  final public No atribuicao_simples() throws ParseException {Token t;
  No noAtrib = new No("ATRIBUICAO_SIMPLES");
  No expr;
    t = jj_consume_token(IDENTIFICADOR);
noAtrib.adicionarFilho(new No("IDENTIFICADOR", t.image));
    t = jj_consume_token(ATRIBUICAO);
inserirTokenUnico(reservada, "ATRIBUICAO", t);
    expr = expressao();
noAtrib.adicionarFilho(expr);
{if ("" != null) return noAtrib;}
    throw new Error("Missing return statement in function");
}

// Nível mais alto da expressão.
  final public No expressao() throws ParseException {No expr;
    expr = expressao_or();
{if ("" != null) return expr;}
    throw new Error("Missing return statement in function");
}

// 12. OPERADORES LÓGICOS (OR)
  final public No expressao_or() throws ParseException {Token t;
  No esq, dir;
    esq = expressao_and();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OR:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_3;
      }
      t = jj_consume_token(OR);
inserirTokenUnico(reservada, "OR", t);
      dir = expressao_and();
No opNode = new No("OPERACAO", t.image);
      opNode.adicionarFilho(esq);
      opNode.adicionarFilho(dir);
      esq = opNode;
    }
{if ("" != null) return esq;}
    throw new Error("Missing return statement in function");
}

// 13. OPERADORES LÓGICOS (AND)
  final public No expressao_and() throws ParseException {Token t;
  No esq, dir;
    esq = expressao_relacional();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:{
        ;
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_4;
      }
      t = jj_consume_token(AND);
inserirTokenUnico(reservada, "AND", t);
      dir = expressao_relacional();
No opNode = new No("OPERACAO", t.image);
      opNode.adicionarFilho(esq);
      opNode.adicionarFilho(dir);
      esq = opNode;
    }
{if ("" != null) return esq;}
    throw new Error("Missing return statement in function");
}

// 14. OPERADORES RELACIONAIS (==, !=, <, >, <=, >=)
  final public No expressao_relacional() throws ParseException {Token t;
  No esq, dir;
    esq = expressao_aritmetica();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IGUAL:
    case DIFERENTE:
    case MENOR:
    case MAIOR:
    case MAIOR_IGUAL:
    case MENOR_IGUAL:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IGUAL:{
        t = jj_consume_token(IGUAL);
inserirTokenUnico(reservada, "IGUAL", t);
        break;
        }
      case DIFERENTE:{
        t = jj_consume_token(DIFERENTE);
inserirTokenUnico(reservada, "DIFERENTE", t);
        break;
        }
      case MENOR:{
        t = jj_consume_token(MENOR);
inserirTokenUnico(reservada, "MENOR", t);
        break;
        }
      case MAIOR:{
        t = jj_consume_token(MAIOR);
inserirTokenUnico(reservada, "MAIOR", t);
        break;
        }
      case MENOR_IGUAL:{
        t = jj_consume_token(MENOR_IGUAL);
inserirTokenUnico(reservada, "MENOR_IGUAL", t);
        break;
        }
      case MAIOR_IGUAL:{
        t = jj_consume_token(MAIOR_IGUAL);
inserirTokenUnico(reservada, "MAIOR_IGUAL", t);
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      dir = expressao_aritmetica();
No opNode = new No("OPERACAO", t.image);
      opNode.adicionarFilho(esq);
      opNode.adicionarFilho(dir);
      esq = opNode;
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      ;
    }
{if ("" != null) return esq;}
    throw new Error("Missing return statement in function");
}

// 15. OPERADORES ARITMÉTICOS (+, -)
  final public No expressao_aritmetica() throws ParseException {Token t;
  No esq, dir;
    esq = termo();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ADICAO:
      case SUBTRACAO:{
        ;
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        break label_5;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ADICAO:{
        t = jj_consume_token(ADICAO);
inserirTokenUnico(reservada, "ADICAO", t);
        break;
        }
      case SUBTRACAO:{
        t = jj_consume_token(SUBTRACAO);
inserirTokenUnico(reservada, "SUBTRACAO", t);
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      dir = termo();
No opNode = new No("OPERACAO", t.image);
                opNode.adicionarFilho(esq);
                opNode.adicionarFilho(dir);
                esq = opNode;
    }
{if ("" != null) return esq;}
    throw new Error("Missing return statement in function");
}

// 16. OPERADORES ARITMÉTICOS (*, /)
  final public No termo() throws ParseException {Token t;
  No esq, dir;
    esq = fator();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLICACAO:
      case DIVISAO:{
        ;
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLICACAO:{
        t = jj_consume_token(MULTIPLICACAO);
inserirTokenUnico(reservada, "MULTIPLICACAO", t);
        break;
        }
      case DIVISAO:{
        t = jj_consume_token(DIVISAO);
inserirTokenUnico(reservada, "DIVISAO", t);
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      dir = fator();
No opNode = new No("OPERACAO", t.image);
      opNode.adicionarFilho(esq);
      opNode.adicionarFilho(dir);
      esq = opNode;
    }
{if ("" != null) return esq;}
    throw new Error("Missing return statement in function");
}

// 17. OPERADORES UNÁRIOS (!, -)
  final public No fator() throws ParseException {Token t;
  No no;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SUBTRACAO:
    case NOT:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SUBTRACAO:{
        t = jj_consume_token(SUBTRACAO);
No opUnario = new No("OP_UNARIO", t.image);
no = fator();
opUnario.adicionarFilho(no);
{if ("" != null) return opUnario;}
        break;
        }
      case NOT:{
        t = jj_consume_token(NOT);
No opUnario = new No("OP_UNARIO", t.image);
      no = fator();
      opUnario.adicionarFilho(no);
      {if ("" != null) return opUnario;}
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    case TOKEN_TRUE:
    case TOKEN_FALSE:
    case ABRE_PARENTESIS:
    case INTEIRO:
    case REAL:
    case IDENTIFICADOR:
    case STRING:{
      no = valor_base();
{if ("" != null) return no;}
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

// Base da recursão das expressões. Define os elementos atômicos.
  final public No valor_base() throws ParseException {Token t;
  No no;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEIRO:{
      t = jj_consume_token(INTEIRO);
no = new No("INTEIRO", t.image);
      no.tipoDado = "integer";
      break;
      }
    case REAL:{
      t = jj_consume_token(REAL);
no = new No("REAL", t.image);
      no.tipoDado = "float";
      break;
      }
    case STRING:{
      t = jj_consume_token(STRING);
no = new No("STRING", t.image);
      no.tipoDado = "string";
      break;
      }
    case TOKEN_TRUE:{
      t = jj_consume_token(TOKEN_TRUE);
no = new No("BOOLEANO", t.image);
      no.tipoDado = "boolean";
      break;
      }
    case TOKEN_FALSE:{
      t = jj_consume_token(TOKEN_FALSE);
no = new No("BOOLEANO", t.image);
      no.tipoDado = "boolean";
      break;
      }
    case IDENTIFICADOR:{
      t = jj_consume_token(IDENTIFICADOR);
no = new No("IDENTIFICADOR", t.image);

      if (tabelaSemantica.lastElement().containsKey(t.image)) {
        no.tipoDado = tabelaSemantica.lastElement().get(t.image);
      }
      else{
        erroSemantico("A vari\u00e1vel '" + t.image + "'n\u00e3o foi declarada.", t);
        no.tipoDado = "erro";
      }
      break;
      }
    case ABRE_PARENTESIS:{
      t = jj_consume_token(ABRE_PARENTESIS);
inserirTokenUnico(reservada, "ABRE_PARENTESIS", t);
      no = expressao();
      t = jj_consume_token(FECHA_PARENTESIS);
inserirTokenUnico(reservada, "FECHA_PARENTESIS", t);
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return no;}
    throw new Error("Missing return statement in function");
}

// Função para declarar variáveis
  final public No declarar_variavel() throws ParseException {Token t, tipoToken;
  No noDecl = new No("DECLARACAO_VARIAVEL");
  No expr;
  String tipoAtual = "";
  No noAtrib = new No("ATRIBUICAO");
  String tipoVariavel = "unknown";
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_INT:{
      tipoToken = jj_consume_token(TOKEN_INT);
tipoAtual = "integer";
      break;
      }
    case TOKEN_FLOAT:{
      tipoToken = jj_consume_token(TOKEN_FLOAT);
tipoAtual = "float";
      break;
      }
    case TOKEN_CHAR:{
      tipoToken = jj_consume_token(TOKEN_CHAR);
tipoAtual = "character";
      break;
      }
    case TOKEN_BOOL:{
      tipoToken = jj_consume_token(TOKEN_BOOL);
tipoAtual = "boolean";
      break;
      }
    case TOKEN_DOUBLE:{
      tipoToken = jj_consume_token(TOKEN_DOUBLE);
tipoAtual = "double";
      break;
      }
    case TOKEN_VOID:{
      tipoToken = jj_consume_token(TOKEN_VOID);
tipoAtual = "void";
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
noDecl.adicionarFilho(new No("TIPO", tipoToken.image));
    inserirTokenUnico(reservada, "TIPO_DADO", tipoToken);
    t = jj_consume_token(IDENTIFICADOR);
noDecl.adicionarFilho(new No("IDENTIFICADOR", t.image));

    if (t.image.length() > MAX) {
      System.out.println("AVISO: IDENTIFICADOR_LONGO: " + t.image);
    }

    inserirTokenUnico(simbolo, "IDENTIFICADOR", t);

    if (tabelaSemantica.lastElement().containsKey(t.image)) {
      erroSemantico("A vari\u00e1vel '" + t.image + "' j\u00e1 foi declarada anteriormente.", t);
    }
    else {
      tabelaSemantica.lastElement().put(t.image, tipoAtual);
    }
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VIRGULA:{
        ;
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        break label_7;
      }
      t = jj_consume_token(VIRGULA);
inserirTokenUnico(reservada, "VIRGULA", t);
      t = jj_consume_token(IDENTIFICADOR);
noDecl.adicionarFilho(new No("IDENTIFICADOR", t.image));

              if (t.image.length() > MAX) {
                System.out.println("AVISO: IDENTIFICADOR_LONGO: " + t.image);
              }

              inserirTokenUnico(simbolo, "IDENTIFICADOR", t);

              if (tabelaSemantica.lastElement().containsKey(t.image)) {
                erroSemantico("A vari\u00e1vel '" + t.image + "' j\u00e1 foi declarada anteriormente.", t);
              }
              else {
                tabelaSemantica.lastElement().put(t.image, tipoAtual);
              }
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ATRIBUICAO:{
if (tabelaSemantica.lastElement().containsKey(t.image)) {
                                tipoVariavel = tabelaSemantica.lastElement().get(t.image);
                        }
                        else {
                                erroSemantico("Vari\u00e1vel n\u00e3o declarada: " + t.image, t);
                        }
      jj_consume_token(ATRIBUICAO);
inserirTokenUnico(reservada, "ATRIBUICAO", t);
      expr = expressao();
noAtrib.adicionarFilho(expr);

                    if (!tipoVariavel.equals("unknown") && expr.tipoDado != null && !expr.tipoDado.equals("erro")) {
                      if (!tipoVariavel.equals(expr.tipoDado)) {
                        erroSemantico("Tipos incompat\u00edveis: vari\u00e1vel do tipo '" + tipoVariavel + "', recebe uma express\u00e3o do tipo: " + expr.tipoDado, t);
                      }
                    }
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      ;
    }
    t = jj_consume_token(PONTO_VIRGULA);
inserirTokenUnico(reservada, "PONTO_VIRGULA", t);
{if ("" != null) return noDecl;}
    throw new Error("Missing return statement in function");
}

// Função para chamada de funções
  final public No chamar_funcao() throws ParseException {Token t;
  No noChamada = new No("CHAMADA_FUNCAO");
  No args = null;
    t = jj_consume_token(IDENTIFICADOR);
noChamada.adicionarFilho(new No("IDENTIFICADOR", t.image));

    if (t.image.length() > MAX) {
      System.out.println("AVISO: IDENTIFICADOR_LONGO: " + t.image);
    }

    inserirTokenUnico(simbolo, "IDENTIFICADOR", t);
    t = jj_consume_token(ABRE_PARENTESIS);
inserirTokenUnico(reservada, "ABRE_PARENTESIS", t);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_TRUE:
    case TOKEN_FALSE:
    case SUBTRACAO:
    case NOT:
    case ABRE_PARENTESIS:
    case INTEIRO:
    case REAL:
    case IDENTIFICADOR:
    case STRING:{
      args = lista_de_argumentos();
      break;
      }
    default:
      jj_la1[24] = jj_gen;
      ;
    }
noChamada.adicionarFilho(args != null ? args : new No("LISTA_ARGUMENTOS_VAZIA"));
    t = jj_consume_token(FECHA_PARENTESIS);
inserirTokenUnico(reservada, "FECHA_PARENTESIS", t);
    t = jj_consume_token(PONTO_VIRGULA);
inserirTokenUnico(reservada, "PONTO_VIRGULA", t);
{if ("" != null) return noChamada;}
    throw new Error("Missing return statement in function");
}

// Regra auxiliar para lista de argumentos em chamadas de função
  final public No lista_de_argumentos() throws ParseException {No noLista = new No("LISTA_ARGUMENTOS");
  No expr;
  Token t;
    expr = expressao();
noLista.adicionarFilho(expr);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VIRGULA:{
        ;
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        break label_8;
      }
      t = jj_consume_token(VIRGULA);
inserirTokenUnico(reservada, "VIRGULA", t);
      expr = expressao();
noLista.adicionarFilho(expr);
    }
{if ("" != null) return noLista;}
    throw new Error("Missing return statement in function");
}

// 20. DEFINIÇÃO DE FUNÇÕES
  final public No criar_funcoes() throws ParseException {Token t, tipoToken;
  No noFuncao = new No("DEFINICAO_FUNCAO");
  No params = null;
  No bloco;
  tabelaSemantica.push(new HashMap<>());
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_VOID:{
      tipoToken = jj_consume_token(TOKEN_VOID);
      break;
      }
    case TOKEN_INT:{
      tipoToken = jj_consume_token(TOKEN_INT);
      break;
      }
    case TOKEN_FLOAT:{
      tipoToken = jj_consume_token(TOKEN_FLOAT);
      break;
      }
    case TOKEN_CHAR:{
      tipoToken = jj_consume_token(TOKEN_CHAR);
      break;
      }
    case TOKEN_BOOL:{
      tipoToken = jj_consume_token(TOKEN_BOOL);
      break;
      }
    case TOKEN_DOUBLE:{
      tipoToken = jj_consume_token(TOKEN_DOUBLE);
      break;
      }
    default:
      jj_la1[26] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
noFuncao.adicionarFilho(new No("TIPO_RETORNO", tipoToken.image));
    inserirTokenUnico(reservada, "TIPO_DADO", tipoToken);
    t = jj_consume_token(IDENTIFICADOR);
noFuncao.adicionarFilho(new No("IDENTIFICADOR", t.image));

    if (t.image.length() > MAX) {
      System.out.println("AVISO: IDENTIFICADOR_LONGO: " + t.image);
    }

    inserirTokenUnico(simbolo, "IDENTIFICADOR", t);
    t = jj_consume_token(ABRE_PARENTESIS);
inserirTokenUnico(reservada, "ABRE_PARENTESIS", t);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_INT:
    case TOKEN_FLOAT:
    case TOKEN_DOUBLE:
    case TOKEN_CHAR:
    case TOKEN_BOOL:{
      params = lista_de_parametros();
      break;
      }
    default:
      jj_la1[27] = jj_gen;
      ;
    }
noFuncao.adicionarFilho(params != null ? params : new No("LISTA_PARAMETROS_VAZIA"));
    t = jj_consume_token(FECHA_PARENTESIS);
inserirTokenUnico(reservada, "FECHA_PARENTESIS", t);
    t = jj_consume_token(ABRE_CHAVES);
inserirTokenUnico(reservada, "ABRE_CHAVES", t);
    bloco = bloco_de_comandos();
noFuncao.adicionarFilho(bloco);
    t = jj_consume_token(FECHA_CHAVES);
inserirTokenUnico(reservada, "FECHA_CHAVES", t);
    tabelaSemantica.pop();
{if ("" != null) return noFuncao;}
    throw new Error("Missing return statement in function");
}

// Regra auxiliar para lista de parâmetros em definições de função
  final public No lista_de_parametros() throws ParseException {Token t, tipoToken;
  No noLista = new No("LISTA_PARAMETROS");
  String tipoParam = "";
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_INT:{
      tipoToken = jj_consume_token(TOKEN_INT);
tipoParam = "integer";
      break;
      }
    case TOKEN_FLOAT:{
      tipoToken = jj_consume_token(TOKEN_FLOAT);
tipoParam = "float";
      break;
      }
    case TOKEN_CHAR:{
      tipoToken = jj_consume_token(TOKEN_CHAR);
tipoParam = "character";
      break;
      }
    case TOKEN_BOOL:{
      tipoToken = jj_consume_token(TOKEN_BOOL);
tipoParam = "boolean";
      break;
      }
    case TOKEN_DOUBLE:{
      tipoToken = jj_consume_token(TOKEN_DOUBLE);
tipoParam = "double";
      break;
      }
    default:
      jj_la1[28] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
inserirTokenUnico(reservada, "TIPO_DADO", tipoToken);
    t = jj_consume_token(IDENTIFICADOR);
inserirTokenUnico(simbolo, "IDENTIFICADOR", t);
tabelaSemantica.lastElement().put(t.image, tipoParam);

    No noParam = new No("PARAMETRO");
    noParam.adicionarFilho(new No("TIPO", tipoToken.image));
    noParam.adicionarFilho(new No("IDENTIFICADOR", t.image));
    noLista.adicionarFilho(noParam);

    if (t.image.length() > MAX) {
      System.out.println("IDENTIFICADOR_LONGO: " + t.image);
    }
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VIRGULA:{
        ;
        break;
        }
      default:
        jj_la1[29] = jj_gen;
        break label_9;
      }
      t = jj_consume_token(VIRGULA);
inserirTokenUnico(reservada, "VIRGULA", t);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_INT:{
        tipoToken = jj_consume_token(TOKEN_INT);
        break;
        }
      case TOKEN_FLOAT:{
        tipoToken = jj_consume_token(TOKEN_FLOAT);
        break;
        }
      case TOKEN_CHAR:{
        tipoToken = jj_consume_token(TOKEN_CHAR);
        break;
        }
      case TOKEN_BOOL:{
        tipoToken = jj_consume_token(TOKEN_BOOL);
        break;
        }
      case TOKEN_DOUBLE:{
        tipoToken = jj_consume_token(TOKEN_DOUBLE);
        break;
        }
      default:
        jj_la1[30] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
inserirTokenUnico(reservada, "TIPO_DADO", tipoToken);
      t = jj_consume_token(IDENTIFICADOR);
inserirTokenUnico(simbolo, "IDENTIFICADOR", t);
if (tabelaSemantica.lastElement().containsKey(t.image)) {
                erroSemantico("A vari\u00e1vel: " + t.image + "j\u00e1 foi declarada!", t);
      }
      else {
        tabelaSemantica.lastElement().put(t.image, tipoParam);
      }
      No noParam1 = new No("PARAMETRO");
      noParam.adicionarFilho(new No("TIPO", tipoToken.image));
      noParam.adicionarFilho(new No("IDENTIFICADOR", t.image));
      noLista.adicionarFilho(noParam);

      if (t.image.length() > MAX) {
        System.out.println("IDENTIFICADOR_LONGO: " + t.image);
      }
    }
{if ("" != null) return noLista;}
    throw new Error("Missing return statement in function");
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_3R_atribuicao_573_9_10()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(ATRIBUICAO)) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_3R_atribuicao_573_9_10()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public JAMTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[31];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x107e000,0x107e000,0x60fec80,0x7e000,0x6080c80,0x100,0x0,0x10300000,0x0,0x10300000,0x0,0x0,0x0,0x0,0x18000000,0x18000000,0x60000000,0x60000000,0x10000000,0x10300000,0x300000,0x7e000,0x0,0x0,0x10300000,0x0,0x7e000,0x7c000,0x7c000,0x0,0x7c000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x200400,0x0,0x200400,0x0,0x200000,0x788100,0x200000,0x788100,0x200,0x80,0x7e,0x7e,0x0,0x0,0x0,0x0,0x100,0x788100,0x788000,0x0,0x800,0x1,0x788100,0x800,0x0,0x0,0x0,0x800,0x0,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[1];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public JAM(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public JAM(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new JAMTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 31; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 31; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public JAM(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new JAMTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 31; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new JAMTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 31; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public JAM(JAMTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 31; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(JAMTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 31; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[61];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 31; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 61; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 1; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
