/* Generated By:JavaCC: Do not edit this line. JAMConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JAMConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TOKEN_IF = 7;
  /** RegularExpression Id. */
  int TOKEN_ELSE = 8;
  /** RegularExpression Id. */
  int TOKEN_SWITCH = 9;
  /** RegularExpression Id. */
  int TOKEN_WHILE = 10;
  /** RegularExpression Id. */
  int TOKEN_FOR = 11;
  /** RegularExpression Id. */
  int TOKEN_DO = 12;
  /** RegularExpression Id. */
  int TOKEN_VOID = 13;
  /** RegularExpression Id. */
  int TOKEN_INT = 14;
  /** RegularExpression Id. */
  int TOKEN_FLOAT = 15;
  /** RegularExpression Id. */
  int TOKEN_DOUBLE = 16;
  /** RegularExpression Id. */
  int TOKEN_CHAR = 17;
  /** RegularExpression Id. */
  int TOKEN_BOOL = 18;
  /** RegularExpression Id. */
  int TOKEN_RETURN = 19;
  /** RegularExpression Id. */
  int TOKEN_TRUE = 20;
  /** RegularExpression Id. */
  int TOKEN_FALSE = 21;
  /** RegularExpression Id. */
  int TOKEN_TRY = 22;
  /** RegularExpression Id. */
  int TOKEN_EXCEPT = 23;
  /** RegularExpression Id. */
  int TOKEN_IMPORT = 24;
  /** RegularExpression Id. */
  int TOKEN_READ = 25;
  /** RegularExpression Id. */
  int TOKEN_WRITE = 26;
  /** RegularExpression Id. */
  int ADICAO = 27;
  /** RegularExpression Id. */
  int SUBTRACAO = 28;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 29;
  /** RegularExpression Id. */
  int DIVISAO = 30;
  /** RegularExpression Id. */
  int MODULO = 31;
  /** RegularExpression Id. */
  int ATRIBUICAO = 32;
  /** RegularExpression Id. */
  int IGUAL = 33;
  /** RegularExpression Id. */
  int DIFERENTE = 34;
  /** RegularExpression Id. */
  int MENOR = 35;
  /** RegularExpression Id. */
  int MAIOR = 36;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 37;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 38;
  /** RegularExpression Id. */
  int AND = 39;
  /** RegularExpression Id. */
  int NOT = 40;
  /** RegularExpression Id. */
  int OR = 41;
  /** RegularExpression Id. */
  int PONTO_VIRGULA = 42;
  /** RegularExpression Id. */
  int VIRGULA = 43;
  /** RegularExpression Id. */
  int PONTO = 44;
  /** RegularExpression Id. */
  int ABRE_CHAVES = 45;
  /** RegularExpression Id. */
  int FECHA_CHAVES = 46;
  /** RegularExpression Id. */
  int ABRE_PARENTESIS = 47;
  /** RegularExpression Id. */
  int FECHA_PARENTESIS = 48;
  /** RegularExpression Id. */
  int ABRE_COLCHETES = 49;
  /** RegularExpression Id. */
  int FECHA_COLCHETES = 50;
  /** RegularExpression Id. */
  int INTEIRO = 51;
  /** RegularExpression Id. */
  int REAL = 52;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 53;
  /** RegularExpression Id. */
  int STRING = 54;
  /** RegularExpression Id. */
  int IDENTIFICADOR_INVALIDO = 55;
  /** RegularExpression Id. */
  int STRING_INVALIDA = 56;
  /** RegularExpression Id. */
  int REAL_INVALIDO = 57;
  /** RegularExpression Id. */
  int DIGITO = 58;
  /** RegularExpression Id. */
  int LETRA = 59;
  /** RegularExpression Id. */
  int SIMBOLO_INVALIDO = 60;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"if\"",
    "\"else\"",
    "\"switch\"",
    "\"while\"",
    "\"for\"",
    "\"do\"",
    "\"void\"",
    "\"integer\"",
    "\"float\"",
    "\"double\"",
    "\"character\"",
    "\"boolean\"",
    "\"return\"",
    "\"true\"",
    "\"false\"",
    "\"try\"",
    "\"except\"",
    "\"import\"",
    "\"read\"",
    "\"write\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\">=\"",
    "\"<=\"",
    "\"&&\"",
    "\"!\"",
    "\"||\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<INTEIRO>",
    "<REAL>",
    "<IDENTIFICADOR>",
    "<STRING>",
    "<IDENTIFICADOR_INVALIDO>",
    "<STRING_INVALIDA>",
    "<REAL_INVALIDO>",
    "<DIGITO>",
    "<LETRA>",
    "<SIMBOLO_INVALIDO>",
  };

}
