/* Lexico.java */
/* Generated By:JavaCC: Do not edit this line. Lexico.java */
import java.util.Scanner;
import java.util.LinkedList;
import java.io.FileInputStream;
import java.io.FileNotFoundException;

class InfoToken {
    String tipo;
    String lexema;
    int linha;
    int coluna;

    public InfoToken(String tipo, String lexema, int linha, int coluna) {
        this.tipo = tipo;
        this.lexema = lexema;
        this.linha = linha;
        this.coluna = coluna;
    }

    @Override
    public String toString() {
        return String.format("Tipo: %s\nLexema: <'%s'>\nLinha: %d, Coluna: %d\n", this.tipo, this.lexema, this.linha, this.coluna);
    }
}

public class Lexico implements LexicoConstants {
    public static LinkedList<InfoToken> reservada = new LinkedList<>();
    public static LinkedList<InfoToken> simbolo = new LinkedList<>();
    private static final int MAX = 32;

    public static void main(String[] args) throws ParseException, TokenMgrError, FileNotFoundException {
        Lexico parser;
        FileInputStream arquivo;
        Scanner scanner = new Scanner(System.in);

        try {
            arquivo = new FileInputStream("fonte_1.txt");
        }
        catch(FileNotFoundException e) {
            System.out.println(e);
            return;
        }

        try {
            parser = new Lexico(arquivo);
            parser.inicializar_programa();
                }
                catch(ParseException e) {
            System.out.println("Erro de sintaxe: " + e.getMessage());
        }
        catch(TokenMgrError e) {
            System.out.println("Erro l\u00e9xico: " + e.getMessage());
        }
        scanner.close();
    }

    public void inserirTokenUnico(LinkedList<InfoToken> l, String tipo, Token t) {
        for (InfoToken tok : l) {
            if (tok.lexema.equals(t.image)) {
                return;
            }
        }
        l.add(new InfoToken(tipo, t.image, t.beginLine, t.beginColumn));
    }

    public void imprimirTokens(LinkedList<InfoToken> l) {
        if (l.isEmpty()) {
            System.out.println("Lista vazia");
            return;
        }
        for (InfoToken tok : l) {
            System.out.println(tok);
        }
    }

// Sintático


// 1. BIBLIOTECAS
  final public void inicializar_programa() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_IMPORT:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      inclusao_biblioteca();
    }
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_VOID:
      case TOKEN_INT:
      case TOKEN_FLOAT:
      case TOKEN_CHAR:
      case TOKEN_BOOL:
      case TOKEN_DOUBLE:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      criar_funcoes();
    }
    jj_consume_token(0);
System.out.println("Programa finalizado.");
}

  final public void inclusao_biblioteca() throws ParseException {Token t;
    t = jj_consume_token(TOKEN_IMPORT);
inserirTokenUnico(reservada, "IMPORT", t);
    t = jj_consume_token(STRING);
inserirTokenUnico(simbolo, "STRING", t);
    t = jj_consume_token(PONTO_VIRGULA);
inserirTokenUnico(reservada, "PONTO_VIRGULA", t);
                                         System.out.println("Biblioteca importada");
}

// 2. BLOCO DE COMANDOS
  final public void bloco_de_comandos() throws ParseException {
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_IF:
      case TOKEN_WHILE:
      case TOKEN_FOR:
      case TOKEN_INT:
      case TOKEN_FLOAT:
      case TOKEN_CHAR:
      case TOKEN_BOOL:
      case TOKEN_RETURN:
      case TOKEN_DOUBLE:
      case TOKEN_READ:
      case TOKEN_WRITE:
      case PONTO_VIRGULA:
      case IDENTIFICADOR:{
        ;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        break label_3;
      }
      comando();
    }
}

// Regra unica de comando.
  final public void comando() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_INT:
    case TOKEN_FLOAT:
    case TOKEN_CHAR:
    case TOKEN_BOOL:
    case TOKEN_DOUBLE:{
      declarar_variavel();
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      if (jj_2_1(2)) {
        atribuicao();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFICADOR:{
          chamar_funcao();
          break;
          }
        case TOKEN_IF:{
          if_else();
          break;
          }
        case TOKEN_WHILE:{
          laco_while();
          break;
          }
        case TOKEN_FOR:{
          laco_for();
          break;
          }
        case TOKEN_RETURN:{
          retorno();
          break;
          }
        case TOKEN_WRITE:{
          comando_escrita();
          break;
          }
        case TOKEN_READ:{
          comando_leitura();
          break;
          }
        case PONTO_VIRGULA:{
          t = jj_consume_token(PONTO_VIRGULA);
inserirTokenUnico(reservada, "PONTO_VIRGULA", t);
          break;
          }
        default:
          jj_la1[4] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
}

// Estrutura condicional if/else.
  final public void if_else() throws ParseException {Token t;
    t = jj_consume_token(TOKEN_IF);
inserirTokenUnico(reservada, "IF", t);
    t = jj_consume_token(ABRE_PARENTESIS);
inserirTokenUnico(reservada, "ABRE_PARENTESIS", t);
    expressao();
    t = jj_consume_token(FECHA_PARENTESIS);
inserirTokenUnico(reservada, "FECHA_PARENTESIS", t);
    t = jj_consume_token(ABRE_CHAVES);
inserirTokenUnico(reservada, "ABRE_CHAVES", t);
    bloco_de_comandos();
    t = jj_consume_token(FECHA_CHAVES);
inserirTokenUnico(reservada, "FECHA_CHAVES", t);
                                                System.out.println("If criado");
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_ELSE:{
      senao();
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
}

  final public void senao() throws ParseException {Token t;
    t = jj_consume_token(TOKEN_ELSE);
inserirTokenUnico(reservada, "ELSE", t);
    t = jj_consume_token(ABRE_CHAVES);
inserirTokenUnico(reservada, "ABRE_CHAVES", t);
    bloco_de_comandos();
    t = jj_consume_token(FECHA_CHAVES);
inserirTokenUnico(reservada, "FECHA_CHAVES", t);
                                                System.out.println("Else criado");
}

// Laço de repetição while.
  final public void laco_while() throws ParseException {Token t;
    t = jj_consume_token(TOKEN_WHILE);
inserirTokenUnico(reservada, "WHILE", t);
    t = jj_consume_token(ABRE_PARENTESIS);
inserirTokenUnico(reservada, "ABRE_PARENTESIS", t);
    expressao();
    t = jj_consume_token(FECHA_PARENTESIS);
inserirTokenUnico(reservada, "FECHA_PARENTESIS", t);
    t = jj_consume_token(ABRE_CHAVES);
inserirTokenUnico(reservada, "ABRE_CHAVES", t);
    bloco_de_comandos();
    t = jj_consume_token(FECHA_CHAVES);
inserirTokenUnico(reservada, "FECHA_CHAVES", t);
                                         System.out.println("While criado");
}

// Laço de repetição for.
  final public void laco_for() throws ParseException {Token t;
    t = jj_consume_token(TOKEN_FOR);
inserirTokenUnico(reservada, "FOR", t);
    t = jj_consume_token(ABRE_PARENTESIS);
inserirTokenUnico(reservada, "ABRE_PARENTESIS", t);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      atribuicao_simples();
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    t = jj_consume_token(PONTO_VIRGULA);
inserirTokenUnico(reservada, "PONTO_VIRGULA", t);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_TRUE:
    case TOKEN_FALSE:
    case SUBTRACAO:
    case NOT:
    case ABRE_PARENTESIS:
    case INTEIRO:
    case REAL:
    case IDENTIFICADOR:
    case STRING:{
      expressao();
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
    t = jj_consume_token(PONTO_VIRGULA);
inserirTokenUnico(reservada, "PONTO_VIRGULA", t);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      atribuicao_simples();
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
    t = jj_consume_token(FECHA_PARENTESIS);
inserirTokenUnico(reservada, "FECHA_PARENTESIS", t);
    t = jj_consume_token(ABRE_CHAVES);
inserirTokenUnico(reservada, "ABRE_CHAVES", t);
    bloco_de_comandos();
    t = jj_consume_token(FECHA_CHAVES);
inserirTokenUnico(reservada, "FECHA_CHAVES", t);
}

// Comando de escrita de dados.
  final public void comando_escrita() throws ParseException {Token t;
    t = jj_consume_token(TOKEN_WRITE);
inserirTokenUnico(reservada, "WRITE", t);
    t = jj_consume_token(ABRE_PARENTESIS);
inserirTokenUnico(reservada, "ABRE_PARENTESIS", t);
    lista_de_argumentos();
    t = jj_consume_token(FECHA_PARENTESIS);
inserirTokenUnico(reservada, "FECHA_PARENTESIS", t);
    t = jj_consume_token(PONTO_VIRGULA);
inserirTokenUnico(reservada, "PONTO_VIRGULA", t);
}

// Comando de leitura de dados.
  final public void comando_leitura() throws ParseException {Token t;
    t = jj_consume_token(TOKEN_READ);
inserirTokenUnico(reservada, "READ", t);
    t = jj_consume_token(ABRE_PARENTESIS);
inserirTokenUnico(reservada, "ABRE_PARENTESIS", t);
    t = jj_consume_token(IDENTIFICADOR);
inserirTokenUnico(simbolo, "IDENTIFICADOR", t);
    t = jj_consume_token(FECHA_PARENTESIS);
inserirTokenUnico(reservada, "FECHA_PARENTESIS", t);
    t = jj_consume_token(PONTO_VIRGULA);
inserirTokenUnico(reservada, "PONTO_VIRGULA", t);
}

// Comando de retorno de função.
  final public void retorno() throws ParseException {Token t;
    t = jj_consume_token(TOKEN_RETURN);
inserirTokenUnico(reservada, "RETURN", t);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_TRUE:
    case TOKEN_FALSE:
    case SUBTRACAO:
    case NOT:
    case ABRE_PARENTESIS:
    case INTEIRO:
    case REAL:
    case IDENTIFICADOR:
    case STRING:{
      expressao();
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    t = jj_consume_token(PONTO_VIRGULA);
inserirTokenUnico(reservada, "PONTO_VIRGULA", t);
                                          System.out.println("Retorno");
}

// 11. ATRIBUIÇÕES
  final public void atribuicao() throws ParseException {Token t;
    t = jj_consume_token(IDENTIFICADOR);
inserirTokenUnico(simbolo, "IDENTIFICADOR", t);
    t = jj_consume_token(ATRIBUICAO);
inserirTokenUnico(reservada, "ATRIBUICAO", t);
    expressao();
    t = jj_consume_token(PONTO_VIRGULA);
inserirTokenUnico(reservada, "PONTO_VIRGULA", t);
                                                System.out.println("Atribui\u00e7\u00e3o");
}

// Regra auxiliar para o laço 'for', que é uma atribuição sem o ponto e vírgula final.
  final public void atribuicao_simples() throws ParseException {Token t;
    t = jj_consume_token(IDENTIFICADOR);
inserirTokenUnico(simbolo, "IDENTIFICADOR", t);
    t = jj_consume_token(ATRIBUICAO);
inserirTokenUnico(reservada, "ATRIBUICAO", t);
    expressao();
}

// Nível mais alto da expressão. Começa com o operador de menor precedência (OR).
  final public void expressao() throws ParseException {
    expressao_or();
}

// 12. OPERADORES LÓGICOS (OR)
  final public void expressao_or() throws ParseException {Token t;
    expressao_and();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OR:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_4;
      }
      t = jj_consume_token(OR);
inserirTokenUnico(reservada, "OR", t);
      expressao_and();
    }
}

// 13. OPERADORES LÓGICOS (AND)
  final public void expressao_and() throws ParseException {Token t;
    expressao_relacional();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:{
        ;
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_5;
      }
      t = jj_consume_token(AND);
inserirTokenUnico(reservada, "AND", t);
      expressao_relacional();
    }
}

// 14. OPERADORES RELACIONAIS (==, !=, <, >, <=, >=)
  final public void expressao_relacional() throws ParseException {Token t;
    expressao_aritmetica();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IGUAL:
    case DIFERENTE:
    case MENOR:
    case MAIOR:
    case MAIOR_IGUAL:
    case MENOR_IGUAL:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IGUAL:{
        t = jj_consume_token(IGUAL);
inserirTokenUnico(reservada, "IGUAL", t);
        break;
        }
      case DIFERENTE:{
        t = jj_consume_token(DIFERENTE);
inserirTokenUnico(reservada, "DIFERENTE", t);
        break;
        }
      case MENOR:{
        t = jj_consume_token(MENOR);
inserirTokenUnico(reservada, "MENOR", t);
        break;
        }
      case MAIOR:{
        t = jj_consume_token(MAIOR);
inserirTokenUnico(reservada, "MAIOR", t);
        break;
        }
      case MENOR_IGUAL:{
        t = jj_consume_token(MENOR_IGUAL);
inserirTokenUnico(reservada, "MENOR_IGUAL", t);
        break;
        }
      case MAIOR_IGUAL:{
        t = jj_consume_token(MAIOR_IGUAL);
inserirTokenUnico(reservada, "MAIOR_IGUAL", t);
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      expressao_aritmetica();
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      ;
    }
}

// 15. OPERADORES ARITMÉTICOS (+, -)
  final public void expressao_aritmetica() throws ParseException {Token t;
    termo();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ADICAO:
      case SUBTRACAO:{
        ;
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ADICAO:{
        t = jj_consume_token(ADICAO);
inserirTokenUnico(reservada, "ADICAO", t);
        break;
        }
      case SUBTRACAO:{
        t = jj_consume_token(SUBTRACAO);
inserirTokenUnico(reservada, "SUBTRACAO", t);
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      termo();
    }
}

// 16. OPERADORES ARITMÉTICOS (*, /)
  final public void termo() throws ParseException {Token t;
    fator();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLICACAO:
      case DIVISAO:{
        ;
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        break label_7;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLICACAO:{
        t = jj_consume_token(MULTIPLICACAO);
inserirTokenUnico(reservada, "MULTIPLICACAO", t);
        break;
        }
      case DIVISAO:{
        t = jj_consume_token(DIVISAO);
inserirTokenUnico(reservada, "DIVISAO", t);
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      fator();
    }
}

// 17. OPERADORES UNÁRIOS (!, -)
  final public void fator() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SUBTRACAO:
    case NOT:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SUBTRACAO:{
        t = jj_consume_token(SUBTRACAO);
inserirTokenUnico(reservada, "SUBTRACAO", t);
        break;
        }
      case NOT:{
        t = jj_consume_token(NOT);
inserirTokenUnico(reservada, "NOT", t);
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      fator();
      break;
      }
    case TOKEN_TRUE:
    case TOKEN_FALSE:
    case ABRE_PARENTESIS:
    case INTEIRO:
    case REAL:
    case IDENTIFICADOR:
    case STRING:{
      valor_base();
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

// Base da recursão das expressões. Define os elementos atômicos.
  final public void valor_base() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEIRO:{
      t = jj_consume_token(INTEIRO);
inserirTokenUnico(simbolo, "INTEIRO", t);
      break;
      }
    case REAL:{
      t = jj_consume_token(REAL);
inserirTokenUnico(simbolo, "REAL", t);
      break;
      }
    case STRING:{
      t = jj_consume_token(STRING);
inserirTokenUnico(simbolo, "STRING", t);
      break;
      }
    case TOKEN_TRUE:{
      t = jj_consume_token(TOKEN_TRUE);
inserirTokenUnico(reservada, "TRUE", t);
      break;
      }
    case TOKEN_FALSE:{
      t = jj_consume_token(TOKEN_FALSE);
inserirTokenUnico(reservada, "FALSE", t);
      break;
      }
    case IDENTIFICADOR:{
      t = jj_consume_token(IDENTIFICADOR);
inserirTokenUnico(simbolo, "IDENTIFICADOR", t);
      break;
      }
    case ABRE_PARENTESIS:{
      t = jj_consume_token(ABRE_PARENTESIS);
inserirTokenUnico(reservada, "ABRE_PARENTESIS", t);
      expressao();
      t = jj_consume_token(FECHA_PARENTESIS);
inserirTokenUnico(reservada, "FECHA_PARENTESIS", t);
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

// Função para declarar variáveis
  final public void declarar_variavel() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_INT:{
      t = jj_consume_token(TOKEN_INT);
inserirTokenUnico(reservada, "INTEGER", t);
      break;
      }
    case TOKEN_FLOAT:{
      t = jj_consume_token(TOKEN_FLOAT);
inserirTokenUnico(reservada, "FLOAT", t);
      break;
      }
    case TOKEN_CHAR:{
      t = jj_consume_token(TOKEN_CHAR);
inserirTokenUnico(reservada, "CHAR", t);
      break;
      }
    case TOKEN_BOOL:{
      t = jj_consume_token(TOKEN_BOOL);
inserirTokenUnico(reservada, "BOOLEAN", t);
      break;
      }
    case TOKEN_DOUBLE:{
      t = jj_consume_token(TOKEN_DOUBLE);
inserirTokenUnico(reservada, "DOUBLE", t);
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    t = jj_consume_token(IDENTIFICADOR);
if(t.image.length() > MAX){
                System.out.println("IDENTIFICADOR_LONGO: "+ t.image);
        }
        else{
                inserirTokenUnico(simbolo, "IDENTIFICADOR", t);
        }
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VIRGULA:{
        ;
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        break label_8;
      }
      t = jj_consume_token(VIRGULA);
inserirTokenUnico(reservada, "VIRGULA", t);
      t = jj_consume_token(IDENTIFICADOR);
if(t.image.length() > MAX){
                System.out.println("IDENTIFICADOR_LONGO: "+ t.image);
        }
        else{
                inserirTokenUnico(simbolo, "IDENTIFICADOR", t);
        }
    }
    t = jj_consume_token(PONTO_VIRGULA);
inserirTokenUnico(reservada, "PONTO_VIRGULA", t);
                                          System.out.println("Declarar vari\u00e1vel");
}

// Função para chamada de funções
  final public void chamar_funcao() throws ParseException {Token t;
    t = jj_consume_token(IDENTIFICADOR);
if(t.image.length() > MAX){
                System.out.println("IDENTIFICADOR_LONGO: "+ t.image);
        }
        else{
                inserirTokenUnico(simbolo, "IDENTIFICADOR", t);
        }
    t = jj_consume_token(ABRE_PARENTESIS);
inserirTokenUnico(reservada, "ABRE_PARENTESIS", t);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_TRUE:
    case TOKEN_FALSE:
    case SUBTRACAO:
    case NOT:
    case ABRE_PARENTESIS:
    case INTEIRO:
    case REAL:
    case IDENTIFICADOR:
    case STRING:{
      lista_de_argumentos();
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      ;
    }
    t = jj_consume_token(FECHA_PARENTESIS);
inserirTokenUnico(reservada, "FECHA_PARENTESIS", t);
    t = jj_consume_token(PONTO_VIRGULA);
inserirTokenUnico(reservada, "PONTO_VIRGULA", t);
                                                System.out.println("Chamada de fun\u00e7\u00e3o");
}

// Regra auxiliar para lista de argumentos em chamadas de função
  final public void lista_de_argumentos() throws ParseException {Token t;
    expressao();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VIRGULA:{
        ;
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        break label_9;
      }
      t = jj_consume_token(VIRGULA);
inserirTokenUnico(reservada, "VIRGULA", t);
      expressao();
    }
}

// 20. DEFINIÇÃO DE FUNÇÕES
  final public void criar_funcoes() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_VOID:{
      jj_consume_token(TOKEN_VOID);
      break;
      }
    case TOKEN_INT:{
      jj_consume_token(TOKEN_INT);
      break;
      }
    case TOKEN_FLOAT:{
      jj_consume_token(TOKEN_FLOAT);
      break;
      }
    case TOKEN_CHAR:{
      jj_consume_token(TOKEN_CHAR);
      break;
      }
    case TOKEN_BOOL:{
      jj_consume_token(TOKEN_BOOL);
      break;
      }
    case TOKEN_DOUBLE:{
      jj_consume_token(TOKEN_DOUBLE);
      break;
      }
    default:
      jj_la1[25] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    t = jj_consume_token(IDENTIFICADOR);
if(t.image.length() > MAX){
                System.out.println("IDENTIFICADOR_LONGO: "+ t.image);
        }
        else{
                inserirTokenUnico(simbolo, "IDENTIFICADOR", t);
        }
    t = jj_consume_token(ABRE_PARENTESIS);
inserirTokenUnico(reservada, "ABRE_PARENTESIS", t);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_INT:
    case TOKEN_FLOAT:
    case TOKEN_CHAR:
    case TOKEN_BOOL:
    case TOKEN_DOUBLE:{
      lista_de_parametros();
      break;
      }
    default:
      jj_la1[26] = jj_gen;
      ;
    }
    t = jj_consume_token(FECHA_PARENTESIS);
inserirTokenUnico(reservada, "FECHA_PARENTESIS", t);
    t = jj_consume_token(ABRE_CHAVES);
inserirTokenUnico(reservada, "ABRE_CHAVES", t);
    bloco_de_comandos();
    t = jj_consume_token(FECHA_CHAVES);
inserirTokenUnico(reservada, "FECHAS_CHAVES", t);
                                        System.out.println("Fun\u00e7\u00e3o criada");
}

// Regra auxiliar para lista de parâmetros em definições de função
  final public void lista_de_parametros() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TOKEN_INT:{
      t = jj_consume_token(TOKEN_INT);
inserirTokenUnico(reservada, "INTEGER", t);
      break;
      }
    case TOKEN_FLOAT:{
      t = jj_consume_token(TOKEN_FLOAT);
inserirTokenUnico(reservada, "FLOAT", t);
      break;
      }
    case TOKEN_CHAR:{
      t = jj_consume_token(TOKEN_CHAR);
inserirTokenUnico(reservada, "CHAR", t);
      break;
      }
    case TOKEN_BOOL:{
      t = jj_consume_token(TOKEN_BOOL);
inserirTokenUnico(reservada, "BOOLEAN", t);
      break;
      }
    case TOKEN_DOUBLE:{
      t = jj_consume_token(TOKEN_DOUBLE);
inserirTokenUnico(reservada, "DOUBLE", t);
      break;
      }
    default:
      jj_la1[27] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    t = jj_consume_token(IDENTIFICADOR);
if(t.image.length() > MAX){
                System.out.println("AVISO: IDENTIFICADOR_LONGO: "+ t.image);
         }
         else{
                inserirTokenUnico(simbolo, "IDENTIFICADOR", t);
         }
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VIRGULA:{
        ;
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        break label_10;
      }
      jj_consume_token(VIRGULA);
inserirTokenUnico(reservada, "VIRGULA", t);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TOKEN_INT:{
        jj_consume_token(TOKEN_INT);
inserirTokenUnico(reservada, "INTEGER", t);
        break;
        }
      case TOKEN_FLOAT:{
        jj_consume_token(TOKEN_FLOAT);
inserirTokenUnico(reservada, "FLOAT", t);
        break;
        }
      case TOKEN_CHAR:{
        jj_consume_token(TOKEN_CHAR);
inserirTokenUnico(reservada, "CHAR", t);
        break;
        }
      case TOKEN_BOOL:{
        jj_consume_token(TOKEN_BOOL);
inserirTokenUnico(reservada, "BOOLEAN", t);
        break;
        }
      case TOKEN_DOUBLE:{
        jj_consume_token(TOKEN_DOUBLE);
inserirTokenUnico(reservada, "DOUBLE", t);
        break;
        }
      default:
        jj_la1[29] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      t = jj_consume_token(IDENTIFICADOR);
if(t.image.length() > MAX){
                System.out.println("IDENTIFICADOR_LONGO: "+ t.image);
             }
             else{
                inserirTokenUnico(simbolo, "IDENTIFICADOR", t);
             }
    }
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_3_1()
 {
    if (jj_3R_atribuicao_355_9_11()) return true;
    return false;
  }

  private boolean jj_3R_atribuicao_355_9_11()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(ATRIBUICAO)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public LexicoTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[30];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	   jj_la1_init_2();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x1000000,0x8f800,0x609f680,0x8f000,0x6010680,0x100,0x0,0x10060000,0x0,0x10060000,0x0,0x0,0x0,0x0,0x18000000,0x18000000,0x60000000,0x60000000,0x10000000,0x10060000,0x60000,0x8f000,0x0,0x10060000,0x0,0x8f800,0x8f000,0x8f000,0x0,0x8f000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x10020000,0x0,0x10020000,0x0,0x10000000,0x3c400100,0x10000000,0x3c400100,0x200,0x80,0x7e,0x7e,0x0,0x0,0x0,0x0,0x100,0x3c400100,0x3c400000,0x0,0x40000,0x3c400100,0x40000,0x0,0x0,0x0,0x40000,0x0,};
	}
	private static void jj_la1_init_2() {
	   jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[1];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Lexico(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Lexico(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new LexicoTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 30; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 30; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Lexico(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new LexicoTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 30; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new LexicoTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 30; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Lexico(LexicoTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 30; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(LexicoTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 30; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[68];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 30; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		   if ((jj_la1_2[i] & (1<<j)) != 0) {
			 la1tokens[64+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 68; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 1; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
