/* Generated By:JavaCC: Do not edit this line. LexicoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TOKEN_IF = 5;
  /** RegularExpression Id. */
  int TOKEN_ELSE = 6;
  /** RegularExpression Id. */
  int TOKEN_WHILE = 7;
  /** RegularExpression Id. */
  int TOKEN_FOR = 8;
  /** RegularExpression Id. */
  int TOKEN_VOID = 9;
  /** RegularExpression Id. */
  int TOKEN_INT = 10;
  /** RegularExpression Id. */
  int TOKEN_FLOAT = 11;
  /** RegularExpression Id. */
  int TOKEN_CHAR = 12;
  /** RegularExpression Id. */
  int TOKEN_BOOL = 13;
  /** RegularExpression Id. */
  int TOKEN_RETURN = 14;
  /** RegularExpression Id. */
  int TOKEN_TRUE = 15;
  /** RegularExpression Id. */
  int TOKEN_FALSE = 16;
  /** RegularExpression Id. */
  int TOKEN_DOUBLE = 17;
  /** RegularExpression Id. */
  int TOKEN_SWITCH = 18;
  /** RegularExpression Id. */
  int TOKEN_DO = 19;
  /** RegularExpression Id. */
  int TOKEN_TRY = 20;
  /** RegularExpression Id. */
  int TOKEN_EXCEPT = 21;
  /** RegularExpression Id. */
  int TOKEN_IMPORT = 22;
  /** RegularExpression Id. */
  int ADICAO = 23;
  /** RegularExpression Id. */
  int SUBTRACAO = 24;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 25;
  /** RegularExpression Id. */
  int DIVISAO = 26;
  /** RegularExpression Id. */
  int ATRIBUICAO = 27;
  /** RegularExpression Id. */
  int MODULO = 28;
  /** RegularExpression Id. */
  int IGUAL = 29;
  /** RegularExpression Id. */
  int DIFERENTE = 30;
  /** RegularExpression Id. */
  int MENOR = 31;
  /** RegularExpression Id. */
  int MAIOR = 32;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 33;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 34;
  /** RegularExpression Id. */
  int AND = 35;
  /** RegularExpression Id. */
  int NOT = 36;
  /** RegularExpression Id. */
  int OR = 37;
  /** RegularExpression Id. */
  int INCREMENTO = 38;
  /** RegularExpression Id. */
  int DECREMENTO = 39;
  /** RegularExpression Id. */
  int SOMA_ATRIBUICAO = 40;
  /** RegularExpression Id. */
  int SUBTRACAO_ATRIBUICAO = 41;
  /** RegularExpression Id. */
  int MULTIPLICACAO_ATRIBUICAO = 42;
  /** RegularExpression Id. */
  int DIVISAO_ATRIBUICAO = 43;
  /** RegularExpression Id. */
  int MODULO_ATRIBUICAO = 44;
  /** RegularExpression Id. */
  int PONTO_VIRGULA = 45;
  /** RegularExpression Id. */
  int VIRGULA = 46;
  /** RegularExpression Id. */
  int PONTO = 47;
  /** RegularExpression Id. */
  int ABRE_CHAVES = 48;
  /** RegularExpression Id. */
  int FECHA_CHAVES = 49;
  /** RegularExpression Id. */
  int ABRE_PARENTESIS = 50;
  /** RegularExpression Id. */
  int FECHA_PARENTESIS = 51;
  /** RegularExpression Id. */
  int ABRE_COLCHETES = 52;
  /** RegularExpression Id. */
  int FECHA_COLCHETES = 53;
  /** RegularExpression Id. */
  int IDENTIFICADOR_INVALIDO = 54;
  /** RegularExpression Id. */
  int STRING_INVALIDA = 55;
  /** RegularExpression Id. */
  int REAL_INVALIDO = 56;
  /** RegularExpression Id. */
  int INTEIRO = 57;
  /** RegularExpression Id. */
  int REAL = 58;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 59;
  /** RegularExpression Id. */
  int STRING = 60;
  /** RegularExpression Id. */
  int DIGITO = 61;
  /** RegularExpression Id. */
  int LETRA = 62;
  /** RegularExpression Id. */
  int SIMBOLO_INVALIDO = 63;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"void\"",
    "\"integer\"",
    "\"float\"",
    "\"character\"",
    "\"boolean\"",
    "\"return\"",
    "\"true\"",
    "\"false\"",
    "\"double\"",
    "\"switch\"",
    "\"do\"",
    "\"try\"",
    "\"except\"",
    "\"import\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"%\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\">=\"",
    "\"<=\"",
    "\"&&\"",
    "\"!\"",
    "\"||\"",
    "\"++\"",
    "\"--\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%/\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<IDENTIFICADOR_INVALIDO>",
    "<STRING_INVALIDA>",
    "<REAL_INVALIDO>",
    "<INTEIRO>",
    "<REAL>",
    "<IDENTIFICADOR>",
    "<STRING>",
    "<DIGITO>",
    "<LETRA>",
    "<SIMBOLO_INVALIDO>",
  };

}
