/* Generated By:JavaCC: Do not edit this line. LexicoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TOKEN_IF = 5;
  /** RegularExpression Id. */
  int TOKEN_ELSE = 6;
  /** RegularExpression Id. */
  int TOKEN_WHILE = 7;
  /** RegularExpression Id. */
  int TOKEN_FOR = 8;
  /** RegularExpression Id. */
  int TOKEN_VOID = 9;
  /** RegularExpression Id. */
  int TOKEN_INT = 10;
  /** RegularExpression Id. */
  int TOKEN_FLOAT = 11;
  /** RegularExpression Id. */
  int TOKEN_CHAR = 12;
  /** RegularExpression Id. */
  int TOKEN_BOOL = 13;
  /** RegularExpression Id. */
  int TOKEN_RETURN = 14;
  /** RegularExpression Id. */
  int TOKEN_TRUE = 15;
  /** RegularExpression Id. */
  int TOKEN_FALSE = 16;
  /** RegularExpression Id. */
  int TOKEN_DOUBLE = 17;
  /** RegularExpression Id. */
  int TOKEN_SWITCH = 18;
  /** RegularExpression Id. */
  int TOKEN_DO = 19;
  /** RegularExpression Id. */
  int TOKEN_TRY = 20;
  /** RegularExpression Id. */
  int TOKEN_EXCEPT = 21;
  /** RegularExpression Id. */
  int ADICAO = 22;
  /** RegularExpression Id. */
  int SUBTRACAO = 23;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 24;
  /** RegularExpression Id. */
  int DIVISAO = 25;
  /** RegularExpression Id. */
  int ATRIBUICAO = 26;
  /** RegularExpression Id. */
  int MODULO = 27;
  /** RegularExpression Id. */
  int IGUAL = 28;
  /** RegularExpression Id. */
  int DIFERENTE = 29;
  /** RegularExpression Id. */
  int MENOR = 30;
  /** RegularExpression Id. */
  int MAIOR = 31;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 32;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 33;
  /** RegularExpression Id. */
  int AND = 34;
  /** RegularExpression Id. */
  int NOT = 35;
  /** RegularExpression Id. */
  int OR = 36;
  /** RegularExpression Id. */
  int PONTO_VIRGULA = 37;
  /** RegularExpression Id. */
  int VIRGULA = 38;
  /** RegularExpression Id. */
  int PONTO = 39;
  /** RegularExpression Id. */
  int ABRE_CHAVES = 40;
  /** RegularExpression Id. */
  int FECHA_CHAVES = 41;
  /** RegularExpression Id. */
  int ABRE_PARENTESIS = 42;
  /** RegularExpression Id. */
  int FECHA_PARENTESIS = 43;
  /** RegularExpression Id. */
  int ABRE_COLCHETES = 44;
  /** RegularExpression Id. */
  int FECHA_COLCHETES = 45;
  /** RegularExpression Id. */
  int INTEIRO = 46;
  /** RegularExpression Id. */
  int REAL = 47;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 48;
  /** RegularExpression Id. */
  int DIGITO = 49;
  /** RegularExpression Id. */
  int LETRA = 50;
  /** RegularExpression Id. */
  int CARACTER_ILEGAL = 51;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"void\"",
    "\"integer\"",
    "\"float\"",
    "\"character\"",
    "\"boolean\"",
    "\"return\"",
    "\"true\"",
    "\"false\"",
    "\"double\"",
    "\"switch\"",
    "\"do\"",
    "\"try\"",
    "\"except\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"%\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\">=\"",
    "\"<=\"",
    "\"&&\"",
    "\"!\"",
    "\"||\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<INTEIRO>",
    "<REAL>",
    "<IDENTIFICADOR>",
    "<DIGITO>",
    "<LETRA>",
    "<CARACTER_ILEGAL>",
  };

}
