/* Generated By:JavaCC: Do not edit this line. LexicoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TOKEN_IF = 5;
  /** RegularExpression Id. */
  int TOKEN_ELSE = 6;
  /** RegularExpression Id. */
  int TOKEN_WHILE = 7;
  /** RegularExpression Id. */
  int TOKEN_FOR = 8;
  /** RegularExpression Id. */
  int TOKEN_VOID = 9;
  /** RegularExpression Id. */
  int TOKEN_INT = 10;
  /** RegularExpression Id. */
  int TOKEN_FLOAT = 11;
  /** RegularExpression Id. */
  int TOKEN_CHAR = 12;
  /** RegularExpression Id. */
  int TOKEN_BOOL = 13;
  /** RegularExpression Id. */
  int TOKEN_RETURN = 14;
  /** RegularExpression Id. */
  int TOKEN_TRUE = 15;
  /** RegularExpression Id. */
  int TOKEN_FALSE = 16;
  /** RegularExpression Id. */
  int ADICAO = 17;
  /** RegularExpression Id. */
  int SUBTRACAO = 18;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 19;
  /** RegularExpression Id. */
  int DIVISAO = 20;
  /** RegularExpression Id. */
  int ATRIBUICAO = 21;
  /** RegularExpression Id. */
  int MODULO = 22;
  /** RegularExpression Id. */
  int IGUAL = 23;
  /** RegularExpression Id. */
  int DIFERENTE = 24;
  /** RegularExpression Id. */
  int MENOR = 25;
  /** RegularExpression Id. */
  int MAIOR = 26;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 27;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int NOT = 30;
  /** RegularExpression Id. */
  int OR = 31;
  /** RegularExpression Id. */
  int INTEIRO = 32;
  /** RegularExpression Id. */
  int REAL = 33;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 34;
  /** RegularExpression Id. */
  int DIGITO = 35;
  /** RegularExpression Id. */
  int LETRA = 36;
  /** RegularExpression Id. */
  int CARACTER_ILEGAL = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"void\"",
    "\"integer\"",
    "\"float\"",
    "\"character\"",
    "\"boolean\"",
    "\"return\"",
    "\"true\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"%\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\">=\"",
    "\"<=\"",
    "\"&&\"",
    "\"!\"",
    "\"||\"",
    "<INTEIRO>",
    "<REAL>",
    "<IDENTIFICADOR>",
    "<DIGITO>",
    "<LETRA>",
    "<CARACTER_ILEGAL>",
  };

}
